#
# Analyze repository with PSRule for Azure
#


# For PSRule for Azure documentation see:
# https://aka.ms/ps-rule-azure

# For action details see:
# https://aka.ms/ps-rule-action


name: PSRule analysis


# Run for main or PRs against main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:


    - name: Checkout
      uses: actions/checkout@v2.3.5

    - name: Run PSRule analysis

      uses: Microsoft/ps-rule@v1.9.0
      with:
        modules: 'PSRule.Rules.Azure'
